#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT_STUDIO_MANAGER
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KT_DB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlienci(Klienci instance);
    partial void UpdateKlienci(Klienci instance);
    partial void DeleteKlienci(Klienci instance);
    partial void InsertFakturySprzedaz(FakturySprzedaz instance);
    partial void UpdateFakturySprzedaz(FakturySprzedaz instance);
    partial void DeleteFakturySprzedaz(FakturySprzedaz instance);
    partial void InsertPozycjeFaktury(PozycjeFaktury instance);
    partial void UpdatePozycjeFaktury(PozycjeFaktury instance);
    partial void DeletePozycjeFaktury(PozycjeFaktury instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::KT_STUDIO_MANAGER.Properties.Settings.Default.KT_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klienci> Kliencis
		{
			get
			{
				return this.GetTable<Klienci>();
			}
		}
		
		public System.Data.Linq.Table<FakturySprzedaz> FakturySprzedazs
		{
			get
			{
				return this.GetTable<FakturySprzedaz>();
			}
		}
		
		public System.Data.Linq.Table<Platnosc> Platnoscs
		{
			get
			{
				return this.GetTable<Platnosc>();
			}
		}
		
		public System.Data.Linq.Table<PozycjeFaktury> PozycjeFakturies
		{
			get
			{
				return this.GetTable<PozycjeFaktury>();
			}
		}
		
		public System.Data.Linq.Table<Qty> Qties
		{
			get
			{
				return this.GetTable<Qty>();
			}
		}
		
		public System.Data.Linq.Table<StawkaVat> StawkaVats
		{
			get
			{
				return this.GetTable<StawkaVat>();
			}
		}
		
		public System.Data.Linq.Table<TerminPlatnosci> TerminPlatnoscis
		{
			get
			{
				return this.GetTable<TerminPlatnosci>();
			}
		}
		
		public System.Data.Linq.Table<Towary> Towaries
		{
			get
			{
				return this.GetTable<Towary>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klienci")]
	public partial class Klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nazwa1;
		
		private string _Nazwa2;
		
		private string _Nazwa3;
		
		private string _Ulica;
		
		private string _KodMiasto;
		
		private string _NIP;
		
		private string _Telefon;
		
		private string _E_mail;
		
		private string _NazwaSkr;
		
		private int _KlientID;
		
		private bool _Aktywny;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNazwa1Changing(string value);
    partial void OnNazwa1Changed();
    partial void OnNazwa2Changing(string value);
    partial void OnNazwa2Changed();
    partial void OnNazwa3Changing(string value);
    partial void OnNazwa3Changed();
    partial void OnUlicaChanging(string value);
    partial void OnUlicaChanged();
    partial void OnKodMiastoChanging(string value);
    partial void OnKodMiastoChanged();
    partial void OnNIPChanging(string value);
    partial void OnNIPChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnNazwaSkrChanging(string value);
    partial void OnNazwaSkrChanged();
    partial void OnKlientIDChanging(int value);
    partial void OnKlientIDChanged();
    partial void OnAktywnyChanging(bool value);
    partial void OnAktywnyChanged();
    #endregion
		
		public Klienci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa1", DbType="NVarChar(255)")]
		public string Nazwa1
		{
			get
			{
				return this._Nazwa1;
			}
			set
			{
				if ((this._Nazwa1 != value))
				{
					this.OnNazwa1Changing(value);
					this.SendPropertyChanging();
					this._Nazwa1 = value;
					this.SendPropertyChanged("Nazwa1");
					this.OnNazwa1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa2", DbType="NVarChar(255)")]
		public string Nazwa2
		{
			get
			{
				return this._Nazwa2;
			}
			set
			{
				if ((this._Nazwa2 != value))
				{
					this.OnNazwa2Changing(value);
					this.SendPropertyChanging();
					this._Nazwa2 = value;
					this.SendPropertyChanged("Nazwa2");
					this.OnNazwa2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa3", DbType="NVarChar(255)")]
		public string Nazwa3
		{
			get
			{
				return this._Nazwa3;
			}
			set
			{
				if ((this._Nazwa3 != value))
				{
					this.OnNazwa3Changing(value);
					this.SendPropertyChanging();
					this._Nazwa3 = value;
					this.SendPropertyChanged("Nazwa3");
					this.OnNazwa3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulica", DbType="NVarChar(255)")]
		public string Ulica
		{
			get
			{
				return this._Ulica;
			}
			set
			{
				if ((this._Ulica != value))
				{
					this.OnUlicaChanging(value);
					this.SendPropertyChanging();
					this._Ulica = value;
					this.SendPropertyChanged("Ulica");
					this.OnUlicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodMiasto", DbType="NVarChar(255)")]
		public string KodMiasto
		{
			get
			{
				return this._KodMiasto;
			}
			set
			{
				if ((this._KodMiasto != value))
				{
					this.OnKodMiastoChanging(value);
					this.SendPropertyChanging();
					this._KodMiasto = value;
					this.SendPropertyChanged("KodMiasto");
					this.OnKodMiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIP", DbType="NVarChar(255)")]
		public string NIP
		{
			get
			{
				return this._NIP;
			}
			set
			{
				if ((this._NIP != value))
				{
					this.OnNIPChanging(value);
					this.SendPropertyChanging();
					this._NIP = value;
					this.SendPropertyChanged("NIP");
					this.OnNIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(255)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="NVarChar(255)")]
		public string E_mail
		{
			get
			{
				return this._E_mail;
			}
			set
			{
				if ((this._E_mail != value))
				{
					this.OnE_mailChanging(value);
					this.SendPropertyChanging();
					this._E_mail = value;
					this.SendPropertyChanged("E_mail");
					this.OnE_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaSkr", DbType="NVarChar(255)")]
		public string NazwaSkr
		{
			get
			{
				return this._NazwaSkr;
			}
			set
			{
				if ((this._NazwaSkr != value))
				{
					this.OnNazwaSkrChanging(value);
					this.SendPropertyChanging();
					this._NazwaSkr = value;
					this.SendPropertyChanged("NazwaSkr");
					this.OnNazwaSkrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlientID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KlientID
		{
			get
			{
				return this._KlientID;
			}
			set
			{
				if ((this._KlientID != value))
				{
					this.OnKlientIDChanging(value);
					this.SendPropertyChanging();
					this._KlientID = value;
					this.SendPropertyChanged("KlientID");
					this.OnKlientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktywny", DbType="Bit NOT NULL")]
		public bool Aktywny
		{
			get
			{
				return this._Aktywny;
			}
			set
			{
				if ((this._Aktywny != value))
				{
					this.OnAktywnyChanging(value);
					this.SendPropertyChanging();
					this._Aktywny = value;
					this.SendPropertyChanged("Aktywny");
					this.OnAktywnyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FakturySprzedaz")]
	public partial class FakturySprzedaz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NrFaktury;
		
		private System.Nullable<System.DateTime> _DataSprzedazy;
		
		private System.Nullable<short> _Dzien;
		
		private System.Nullable<short> _Miesiac;
		
		private System.Nullable<short> _Rok;
		
		private System.Nullable<int> _KlientID;
		
		private System.Nullable<double> _Netto8;
		
		private System.Nullable<double> _Netto23;
		
		private System.Nullable<double> _Brutto8;
		
		private System.Nullable<double> _Brutto23;
		
		private string _Slownie;
		
		private string _FormaPlatnosci;
		
		private string _Termin;
		
		private EntitySet<PozycjeFaktury> _PozycjeFakturies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNrFakturyChanging(string value);
    partial void OnNrFakturyChanged();
    partial void OnDataSprzedazyChanging(System.Nullable<System.DateTime> value);
    partial void OnDataSprzedazyChanged();
    partial void OnDzienChanging(System.Nullable<short> value);
    partial void OnDzienChanged();
    partial void OnMiesiacChanging(System.Nullable<short> value);
    partial void OnMiesiacChanged();
    partial void OnRokChanging(System.Nullable<short> value);
    partial void OnRokChanged();
    partial void OnKlientIDChanging(System.Nullable<int> value);
    partial void OnKlientIDChanged();
    partial void OnNetto8Changing(System.Nullable<double> value);
    partial void OnNetto8Changed();
    partial void OnNetto23Changing(System.Nullable<double> value);
    partial void OnNetto23Changed();
    partial void OnBrutto8Changing(System.Nullable<double> value);
    partial void OnBrutto8Changed();
    partial void OnBrutto23Changing(System.Nullable<double> value);
    partial void OnBrutto23Changed();
    partial void OnSlownieChanging(string value);
    partial void OnSlownieChanged();
    partial void OnFormaPlatnosciChanging(string value);
    partial void OnFormaPlatnosciChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    #endregion
		
		public FakturySprzedaz()
		{
			this._PozycjeFakturies = new EntitySet<PozycjeFaktury>(new Action<PozycjeFaktury>(this.attach_PozycjeFakturies), new Action<PozycjeFaktury>(this.detach_PozycjeFakturies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrFaktury", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NrFaktury
		{
			get
			{
				return this._NrFaktury;
			}
			set
			{
				if ((this._NrFaktury != value))
				{
					this.OnNrFakturyChanging(value);
					this.SendPropertyChanging();
					this._NrFaktury = value;
					this.SendPropertyChanged("NrFaktury");
					this.OnNrFakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSprzedazy", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataSprzedazy
		{
			get
			{
				return this._DataSprzedazy;
			}
			set
			{
				if ((this._DataSprzedazy != value))
				{
					this.OnDataSprzedazyChanging(value);
					this.SendPropertyChanging();
					this._DataSprzedazy = value;
					this.SendPropertyChanged("DataSprzedazy");
					this.OnDataSprzedazyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dzien", DbType="SmallInt")]
		public System.Nullable<short> Dzien
		{
			get
			{
				return this._Dzien;
			}
			set
			{
				if ((this._Dzien != value))
				{
					this.OnDzienChanging(value);
					this.SendPropertyChanging();
					this._Dzien = value;
					this.SendPropertyChanged("Dzien");
					this.OnDzienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miesiac", DbType="SmallInt")]
		public System.Nullable<short> Miesiac
		{
			get
			{
				return this._Miesiac;
			}
			set
			{
				if ((this._Miesiac != value))
				{
					this.OnMiesiacChanging(value);
					this.SendPropertyChanging();
					this._Miesiac = value;
					this.SendPropertyChanged("Miesiac");
					this.OnMiesiacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rok", DbType="SmallInt")]
		public System.Nullable<short> Rok
		{
			get
			{
				return this._Rok;
			}
			set
			{
				if ((this._Rok != value))
				{
					this.OnRokChanging(value);
					this.SendPropertyChanging();
					this._Rok = value;
					this.SendPropertyChanged("Rok");
					this.OnRokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlientID", DbType="Int")]
		public System.Nullable<int> KlientID
		{
			get
			{
				return this._KlientID;
			}
			set
			{
				if ((this._KlientID != value))
				{
					this.OnKlientIDChanging(value);
					this.SendPropertyChanging();
					this._KlientID = value;
					this.SendPropertyChanged("KlientID");
					this.OnKlientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Netto8", DbType="Float")]
		public System.Nullable<double> Netto8
		{
			get
			{
				return this._Netto8;
			}
			set
			{
				if ((this._Netto8 != value))
				{
					this.OnNetto8Changing(value);
					this.SendPropertyChanging();
					this._Netto8 = value;
					this.SendPropertyChanged("Netto8");
					this.OnNetto8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Netto23", DbType="Float")]
		public System.Nullable<double> Netto23
		{
			get
			{
				return this._Netto23;
			}
			set
			{
				if ((this._Netto23 != value))
				{
					this.OnNetto23Changing(value);
					this.SendPropertyChanging();
					this._Netto23 = value;
					this.SendPropertyChanged("Netto23");
					this.OnNetto23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brutto8", DbType="Float")]
		public System.Nullable<double> Brutto8
		{
			get
			{
				return this._Brutto8;
			}
			set
			{
				if ((this._Brutto8 != value))
				{
					this.OnBrutto8Changing(value);
					this.SendPropertyChanging();
					this._Brutto8 = value;
					this.SendPropertyChanged("Brutto8");
					this.OnBrutto8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brutto23", DbType="Float")]
		public System.Nullable<double> Brutto23
		{
			get
			{
				return this._Brutto23;
			}
			set
			{
				if ((this._Brutto23 != value))
				{
					this.OnBrutto23Changing(value);
					this.SendPropertyChanging();
					this._Brutto23 = value;
					this.SendPropertyChanged("Brutto23");
					this.OnBrutto23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slownie", DbType="NVarChar(255)")]
		public string Slownie
		{
			get
			{
				return this._Slownie;
			}
			set
			{
				if ((this._Slownie != value))
				{
					this.OnSlownieChanging(value);
					this.SendPropertyChanging();
					this._Slownie = value;
					this.SendPropertyChanged("Slownie");
					this.OnSlownieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormaPlatnosci", DbType="NVarChar(255)")]
		public string FormaPlatnosci
		{
			get
			{
				return this._FormaPlatnosci;
			}
			set
			{
				if ((this._FormaPlatnosci != value))
				{
					this.OnFormaPlatnosciChanging(value);
					this.SendPropertyChanging();
					this._FormaPlatnosci = value;
					this.SendPropertyChanged("FormaPlatnosci");
					this.OnFormaPlatnosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(255)")]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FakturySprzedaz_PozycjeFaktury", Storage="_PozycjeFakturies", ThisKey="NrFaktury", OtherKey="NrFaktury")]
		public EntitySet<PozycjeFaktury> PozycjeFakturies
		{
			get
			{
				return this._PozycjeFakturies;
			}
			set
			{
				this._PozycjeFakturies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PozycjeFakturies(PozycjeFaktury entity)
		{
			this.SendPropertyChanging();
			entity.FakturySprzedaz = this;
		}
		
		private void detach_PozycjeFakturies(PozycjeFaktury entity)
		{
			this.SendPropertyChanging();
			entity.FakturySprzedaz = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Platnosc")]
	public partial class Platnosc
	{
		
		private int _ID;
		
		private string _Platność;
		
		public Platnosc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Platność", DbType="NVarChar(255)")]
		public string Platność
		{
			get
			{
				return this._Platność;
			}
			set
			{
				if ((this._Platność != value))
				{
					this._Platność = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PozycjeFaktury")]
	public partial class PozycjeFaktury : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NrFaktury;
		
		private string _Lp;
		
		private string _Nazwa;
		
		private string _Qty;
		
		private System.Nullable<int> _Ilosc;
		
		private System.Nullable<double> _StVat;
		
		private System.Nullable<double> _CenaNetto;
		
		private System.Nullable<double> _WartoscNetto;
		
		private System.Nullable<double> _WartoscVat;
		
		private System.Nullable<double> _WartoscBrutto;
		
		private EntityRef<FakturySprzedaz> _FakturySprzedaz;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNrFakturyChanging(string value);
    partial void OnNrFakturyChanged();
    partial void OnLpChanging(string value);
    partial void OnLpChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnQtyChanging(string value);
    partial void OnQtyChanged();
    partial void OnIloscChanging(System.Nullable<int> value);
    partial void OnIloscChanged();
    partial void OnStVatChanging(System.Nullable<double> value);
    partial void OnStVatChanged();
    partial void OnCenaNettoChanging(System.Nullable<double> value);
    partial void OnCenaNettoChanged();
    partial void OnWartoscNettoChanging(System.Nullable<double> value);
    partial void OnWartoscNettoChanged();
    partial void OnWartoscVatChanging(System.Nullable<double> value);
    partial void OnWartoscVatChanged();
    partial void OnWartoscBruttoChanging(System.Nullable<double> value);
    partial void OnWartoscBruttoChanged();
    #endregion
		
		public PozycjeFaktury()
		{
			this._FakturySprzedaz = default(EntityRef<FakturySprzedaz>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NrFaktury", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NrFaktury
		{
			get
			{
				return this._NrFaktury;
			}
			set
			{
				if ((this._NrFaktury != value))
				{
					if (this._FakturySprzedaz.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNrFakturyChanging(value);
					this.SendPropertyChanging();
					this._NrFaktury = value;
					this.SendPropertyChanged("NrFaktury");
					this.OnNrFakturyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lp", DbType="NVarChar(255)")]
		public string Lp
		{
			get
			{
				return this._Lp;
			}
			set
			{
				if ((this._Lp != value))
				{
					this.OnLpChanging(value);
					this.SendPropertyChanging();
					this._Lp = value;
					this.SendPropertyChanged("Lp");
					this.OnLpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="NVarChar(255)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="NVarChar(255)")]
		public string Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this.OnIloscChanging(value);
					this.SendPropertyChanging();
					this._Ilosc = value;
					this.SendPropertyChanged("Ilosc");
					this.OnIloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StVat", DbType="Float")]
		public System.Nullable<double> StVat
		{
			get
			{
				return this._StVat;
			}
			set
			{
				if ((this._StVat != value))
				{
					this.OnStVatChanging(value);
					this.SendPropertyChanging();
					this._StVat = value;
					this.SendPropertyChanged("StVat");
					this.OnStVatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaNetto", DbType="Float")]
		public System.Nullable<double> CenaNetto
		{
			get
			{
				return this._CenaNetto;
			}
			set
			{
				if ((this._CenaNetto != value))
				{
					this.OnCenaNettoChanging(value);
					this.SendPropertyChanging();
					this._CenaNetto = value;
					this.SendPropertyChanged("CenaNetto");
					this.OnCenaNettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WartoscNetto", DbType="Float")]
		public System.Nullable<double> WartoscNetto
		{
			get
			{
				return this._WartoscNetto;
			}
			set
			{
				if ((this._WartoscNetto != value))
				{
					this.OnWartoscNettoChanging(value);
					this.SendPropertyChanging();
					this._WartoscNetto = value;
					this.SendPropertyChanged("WartoscNetto");
					this.OnWartoscNettoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WartoscVat", DbType="Float")]
		public System.Nullable<double> WartoscVat
		{
			get
			{
				return this._WartoscVat;
			}
			set
			{
				if ((this._WartoscVat != value))
				{
					this.OnWartoscVatChanging(value);
					this.SendPropertyChanging();
					this._WartoscVat = value;
					this.SendPropertyChanged("WartoscVat");
					this.OnWartoscVatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WartoscBrutto", DbType="Float")]
		public System.Nullable<double> WartoscBrutto
		{
			get
			{
				return this._WartoscBrutto;
			}
			set
			{
				if ((this._WartoscBrutto != value))
				{
					this.OnWartoscBruttoChanging(value);
					this.SendPropertyChanging();
					this._WartoscBrutto = value;
					this.SendPropertyChanged("WartoscBrutto");
					this.OnWartoscBruttoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FakturySprzedaz_PozycjeFaktury", Storage="_FakturySprzedaz", ThisKey="NrFaktury", OtherKey="NrFaktury", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public FakturySprzedaz FakturySprzedaz
		{
			get
			{
				return this._FakturySprzedaz.Entity;
			}
			set
			{
				FakturySprzedaz previousValue = this._FakturySprzedaz.Entity;
				if (((previousValue != value) 
							|| (this._FakturySprzedaz.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FakturySprzedaz.Entity = null;
						previousValue.PozycjeFakturies.Remove(this);
					}
					this._FakturySprzedaz.Entity = value;
					if ((value != null))
					{
						value.PozycjeFakturies.Add(this);
						this._NrFaktury = value.NrFaktury;
					}
					else
					{
						this._NrFaktury = default(string);
					}
					this.SendPropertyChanged("FakturySprzedaz");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Qty")]
	public partial class Qty
	{
		
		private int _ID;
		
		private string _Qty1;
		
		public Qty()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Qty", Storage="_Qty1", DbType="NVarChar(255)")]
		public string Qty1
		{
			get
			{
				return this._Qty1;
			}
			set
			{
				if ((this._Qty1 != value))
				{
					this._Qty1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StawkaVat")]
	public partial class StawkaVat
	{
		
		private int _ID;
		
		private System.Nullable<double> _St_VAT;
		
		public StawkaVat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[St VAT]", Storage="_St_VAT", DbType="Float")]
		public System.Nullable<double> St_VAT
		{
			get
			{
				return this._St_VAT;
			}
			set
			{
				if ((this._St_VAT != value))
				{
					this._St_VAT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TerminPlatnosci")]
	public partial class TerminPlatnosci
	{
		
		private int _ID;
		
		private string _Termin;
		
		public TerminPlatnosci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(255)")]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this._Termin = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Towary")]
	public partial class Towary
	{
		
		private int _ID;
		
		private string _NazwaTowaru;
		
		public Towary()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwaTowaru", DbType="NVarChar(255)")]
		public string NazwaTowaru
		{
			get
			{
				return this._NazwaTowaru;
			}
			set
			{
				if ((this._NazwaTowaru != value))
				{
					this._NazwaTowaru = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
